/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ASUS
 */
public class latihan3view extends javax.swing.JFrame {

    /**
     * Creates new form latihan3view
     */
    public latihan3view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        minat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoutput = new javax.swing.JTextArea();
        txtnama = new javax.swing.JTextField();
        buttonmale = new javax.swing.JRadioButton();
        buttonfemale = new javax.swing.JRadioButton();
        xjurusan = new javax.swing.JComboBox<>();
        programming = new javax.swing.JCheckBox();
        design = new javax.swing.JCheckBox();
        game = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI PENDATAAN VOLUNTER PENDATAAN VOLUNTER DEV SUMMIT");

        output.setText("Output:");

        nama.setText("Nama");

        jeniskelamin.setText("Jenis Kelamin");

        jurusan.setText("Jurusan");

        minat.setText("Minat");

        jLabel7.setText("Area Penempatan ");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textoutput.setColumns(20);
        textoutput.setRows(5);
        jScrollPane1.setViewportView(textoutput);

        buttonmale.setText("Male");

        buttonfemale.setText("Female");

        xjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desain Komunikasi Visual", "Teknik Informatika", "Teknik Industri", "Sastra Inggris" }));
        xjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjurusanActionPerformed(evt);
            }
        });

        programming.setText("Programming");

        design.setText("Design UI UX");

        game.setText("Game");
        game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameActionPerformed(evt);
            }
        });

        area.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Dev Summit Bandung", "Dev Summit Jakarta", "Dev Summit Surabaya", "Dev Summit Yogyakarta" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nama)
                        .addContainerGap(772, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minat)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programming)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonmale)
                            .addComponent(buttonfemale)
                            .addComponent(design)
                            .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(output)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jurusan)
                            .addComponent(jeniskelamin))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(output))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jeniskelamin)
                            .addComponent(buttonmale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonfemale)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jurusan)
                            .addComponent(xjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minat)
                            .addComponent(programming))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(design)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(game)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xjurusanActionPerformed

    private void gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        latihan3 olat= new latihan3();       
        String nama,jurusan,areapenempatan;
        nama= txtnama.getText();
        
        String jeniskelamin="";
        if (buttonmale.isSelected()){
            jeniskelamin= buttonmale.getText();
        }
        else if (buttonfemale.isSelected()){
            jeniskelamin= buttonfemale.getText();
        }
        
        String minat= "";
        if(programming.isSelected()) {
            minat= programming.getText();
        }
        else if (design.isSelected()){
            minat= design.getText();
        }
        else if (game.isSelected()){
            minat= game.getText();
        }
        
        
        textoutput.setText("Nama:"+nama
                + "\nJenis Kelamin:"+ jeniskelamin
                + "\nJurusan:"+ xjurusan.getSelectedItem()
                + "\nMinat:"+minat
                + "\nKota Penempatan:"+area.getSelectedValue().toString());
 
        // TODO add your handling code here:
        
        /*
          String nama = txtNama.getText();
        String jeniskelamin = "";
        if (rbtnLakilaki.isSelected()) {
            jeniskelamin = rbtnLakilaki.getText();
        } else if (rbtnPerempuan.isSelected()) {
            jeniskelamin = rbtnPerempuan.getText();
        }
        String minat = "";
        if (checkboxProgramming.isSelected()) {
            minat = minat + "" + checkboxProgramming.getText();
        }
        if (checkboxGame.isSelected()) {
            minat = minat + "" + checkboxGame.getText();
        }
        if (checkboxDesain.isSelected()) {
            minat = minat + "" + checkboxDesain.getText();
        }
        txtareaOutput.setText("Nama : " + nama
                + "\nJenis Kelamin : " + jeniskelamin
                + "\nJurusan : " + cbJurusan.getSelectedItem()
                + "\nMinat : " + minat
                + "\nKota Penempatan : "+ listArea.getSelectedValue().toString());
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan3view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan3view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan3view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan3view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan3view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> area;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonfemale;
    private javax.swing.JRadioButton buttonmale;
    private javax.swing.JCheckBox design;
    private javax.swing.JCheckBox game;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JLabel jurusan;
    private javax.swing.JLabel minat;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel output;
    private javax.swing.JCheckBox programming;
    private javax.swing.JTextArea textoutput;
    private javax.swing.JTextField txtnama;
    private javax.swing.JComboBox<String> xjurusan;
    // End of variables declaration//GEN-END:variables
}
